import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMock = process.env.NEXT_PUBLIC_USE_MOCK_LLM === "true";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isMock && (
          <div
            style={{
              background: "#fde68a",
              color: "#92400e",
              padding: "8px 12px",
              fontSize: "14px",
              textAlign: "center",
              borderBottom: "1px solid #f59e0b",
            }}
          >
            ⚠️ Mock Mode enabled — AI responses are simulated
          </div>
        )}
        {children}
      </body>
    </html>
  );
}